language: node_js
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/44de3da44f4cbb9a4bbd
  on_success: always
  on_failure: always
node_js:
- '0.12'
- '0.11'
- '0.10'
